### ISSUE TITLE
Tweak: DarkPapers - Settings App Freezes ...

### ISSUE THREAD

**Issue by TomKFL** [alexPNG/alexpng.github.io#2]
At first i need to say it is a nice tweak with a bunch of nice Wallpapers.
Thanks for that🙃

iPhone: XS Max, iOS 13.3, Uncover 4.0.3
Cr4shed won‘t show anything.
So I can‘t provide a Crash Log.

I am experiencing some bugs lately
what information do you need?
(Tweaks installed?)

2/3 of the Time I got this:
Settings App Freezes when opening the Wallpapers section -> respring

1/3 of the Time I got this:
Everything in the Wallpapers section (when not freezing) is laggy/slow (choosing a Wallpaper for example or even getting there) [the Apple Original Wallpapers too]

After choosing a Wallpaper and applying it, the spinning circle with the (i dont remember the exact words) „applying Wallpaper“-Banner won't disapear and the Phone reboots (NO respring) or needs a „Hard Reboot“ after starting the Phone again and re-Jailbreaking it the „choosen“ Wallpaper is selected and working perfectly 😅

(I don't know if the reboot is needed for the Wallpaper Change or not)

**Comment by alexPNG** [comment]
Can you provide a tweak list? AnimationsBeFast and AnimationsBeFastPlus conflict with WallpaperLoader. In case you have either of those, try disabling them and see if the problem persists. Otherwise it is another tweak that’s conflicting with WallpaperLoader. A reboot isn’t necessary to apply the wallpaper. It should work without the need of a reboot/respring.
